name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install pytest
        pip install numpy
        pip install scipy

    - name: Run tests
      run: |
        pytest testFitFunctions.py  # Replace with your actual test file name
