name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install pytest
        pip install numpy
        pip install scipy
        pip install statsmodels
        pip install h5py
        pip install matplotlib

    - name: Run fit-functions tests
      run: |
        pytest tests/test_FitFunctions.py

    - name: Run AnalyzeH5.py and diff against expected plots
      run: |
        cd tests
        pytest test_AnalyzeH5.py